### ISSUE TITLE
Duplicate frequencies in Pactor settings and connect windows

### ISSUE THREAD

**Issue by tmiw** [ARSFI/paclink-open-source#27]
For gateways with multiple frequencies, duplicate frequencies show up in both the settings dialog:

<img width="798" alt="Screen Shot 2022-06-15 at 1 31 33 AM" src="https://user-images.githubusercontent.com/449242/173781599-dbff3e9a-1617-4528-bb50-a92257a18b41.png">

as well as the connection window (see https://github.com/ARSFI/paclink-open-source/discussions/26#discussioncomment-2951720).

**Comment by tmiw** [comment]
@k0qed, I noticed the following while debugging. It seems types 43 and 50 aren't valid modes in Paclink currently:

<img width="453" alt="Screen Shot 2022-06-15 at 1 30 30 AM" src="https://user-images.githubusercontent.com/449242/173781940-2ef1373a-2ef8-4671-8451-6dd5fa113c13.png">

Can you clarify what those are supposed to indicate? I want to make sure I'm not filtering out anything I shouldn't be when I make the fix.

**Comment by k0qed** [comment]
Hi Mooneer,

I'm out camping for a few more days. When I get back I'll get you the full
listing of those codes. I know that the 50's are Vara, but can't recall
what 43 is.

Lee

**Comment by w3qalor** [comment]
Hi Mooneer,

Here’s a list from my docs that may help. Lee can update, but I hope it helps:

0=packet 1200 baud
1=packet 2400 baud
2=packet 4800 baud
3=packet 9600 baud
4=packet 19200 baud
5= packet 38400 baud
6-10=reserved for future packet

11=pactor 1 only
12=pactor 1&2 only
13=pactor 1, 2 & 3
14=pactor 2 only
15=pactor 2&3 only
16=pactor 3 only
17=pactor 1, 2, 3 & 4
18=pactor 2, 3 & 4 only
19=pactor 3 & 4 only
20=pactor 4 only

21= WINMOR 500 (deprecated)
22=WINMOR 1600 (deprecated)

30=SCS Robust Packet

40=ARDOP 200
41=ARDOP 500
42=ARDOP 1000
43=ARDOP 2000
44=ARDOP 2000 FM

50=VARA HF 2.4
53=VARA 500 HF
(other VARA you’ll need to get from Lee or Phil)

—Lor

**Comment by k0qed** [comment]
Here's the current list of recognized modes (and mode combinations used by
gateways):

0: Packet 1200
1: Packet 2400
2: Packet 4800
3: Packet 9600
4: Packet 19200
5: Packet 38400
11: Pactor 1
12: Pactor 1,2
13: Pactor 1,2,3
14: Pactor 2
15: Pactor 2,3
16: Pactor 3
17: Pactor 1,2,3,4
18: Pactor 2,3,4
19: Pactor 3,4
20: Pactor 4
21: WINMOR 500
22: WINMOR 1600
30: Robust Packet
40: ARDOP 200
41: ARDOP 500
42: ARDOP 1000
43: ARDOP 2000
44: ARDOP 2000 FM
50: VARA
51: VARA FM
52: VARA FM WIDE
53: VARA 500
54: VARA 2750

**Comment by tmiw** [comment]
Thanks @w3qalor and @k0qed. Looks like the duplicates I was seeing were for the VARA channels. I went ahead and made some updates to suppress those in the Pactor configuration and released a new build: https://github.com/ARSFI/paclink-open-source/releases/tag/nightly_20220617
