### ISSUE TITLE
Message size limit never used

### ISSUE THREAD

**Issue by k0qed** [ARSFI/paclink-open-source#6]
In module DialogSiteProperties the account setting for message size limit is never used. It should be removed.

**Comment by tmiw** [comment]
Removed. 

BTW, looks like winlink-webservices is still using the incorrect path on D:\.

**Comment by k0qed** [comment]
> BTW, looks like winlink-webservices is still using the incorrect path on D:.

I've changed access to that repo to 'write access' for the team. If you would, go ahead and make the change to fix the path. I guess what I changed didn't stick for some reason.

**Comment by tmiw** [comment]
Thanks! I updated that repo and the subprojects in the main Paclink repo to point to the latest commit.
